services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://download.nus.edu.sg/mirror/archlinux/iso/2026.07.01/archlinux-2026.07.01-x86_64.iso"
      RAM_SIZE: "12G"
      CPU_CORES: "6"
      DISK_SIZE: "28G"
      MANUAL: "Y"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
