services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://twds.dl.sourceforge.net/project/blissos-x86/Official/BlissOS14/OpenGApps/Generic/Bliss-v14.10.3-x86_64-OFFICIAL-opengapps-20241012.iso"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "28G"
      MANUAL: "Y"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
